option(BUILD_WITH_DOCS "Generate Docs" OFF)

option(BUILD_TESTS "Build test exe" OFF)

option(CLIB_OBJECT_LIB "Makes Clib an object library" OFF)
if(CLIB_OBJECT_LIB)
  message(STATUS "Build clib as OBJECT")
endif()

option(CLIB_USE_OPENMP "Use openmp if supported" ON)
if(CLIB_USE_OPENMP)
  find_package(OpenMP)
  if(OpenMP_C_FOUND)
    list(APPEND CLIB_COMPILE_OPTIONS ${OpenMP_C_FLAGS})
    list(APPEND CLIB_COMPILE_DEFINITIONS CLIB_USE_OPENMP)
  endif(OpenMP_C_FOUND)
endif(CLIB_USE_OPENMP)

option(SUPPORT_CLANGD "Support clangd" ON)
if(SUPPORT_CLANGD)
  set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
  set(CLANGD_SRC ${CMAKE_CURRENT_SOURCE_DIR}/cmake/.clangd.in)
  set(CLANGD_DEST ${CMAKE_CURRENT_SOURCE_DIR}/.clangd)
  configure_file(${CLANGD_SRC} ${CLANGD_DEST} @ONLY)
endif()
